# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/red-pitaya/red-pitaya-notes/cfg/ports.xdc

# XDC: /home/red-pitaya/red-pitaya-notes/cfg/clocks.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0}]

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}]

# IP: bd/system/ip/system_buf_0_0/system_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_buf_0_0 || ORIG_REF_NAME==system_buf_0_0}]

# IP: bd/system/ip/system_buf_1_0/system_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_buf_1_0 || ORIG_REF_NAME==system_buf_1_0}]

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0}]

# IP: bd/system/ip/system_cntr_0_0/system_cntr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cntr_0_0 || ORIG_REF_NAME==system_cntr_0_0}]

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0}]

# IP: bd/system/ip/system_cfg_0_0/system_cfg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cfg_0_0 || ORIG_REF_NAME==system_cfg_0_0}]

# IP: bd/system/ip/system_ps_0_axi_periph_0/system_ps_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_axi_periph_0 || ORIG_REF_NAME==system_ps_0_axi_periph_0}]

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0}]

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0}]

# IP: bd/system/ip/system_slice_3_0/system_slice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_3_0 || ORIG_REF_NAME==system_slice_3_0}]

# IP: bd/system/ip/system_slice_4_0/system_slice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_slice_4_0 || ORIG_REF_NAME==system_slice_4_0}]

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0}]

# IP: bd/system/ip/system_fifo_0_0/system_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0}]

# IP: bd/system/ip/system_pktzr_0_0/system_pktzr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pktzr_0_0 || ORIG_REF_NAME==system_pktzr_0_0}]

# IP: bd/system/ip/system_const_1_0/system_const_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_1_0 || ORIG_REF_NAME==system_const_1_0}]

# IP: bd/system/ip/system_writer_0_0/system_writer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_writer_0_0 || ORIG_REF_NAME==system_writer_0_0}]

# IP: bd/system/ip/system_conv_0_0/system_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_conv_0_0 || ORIG_REF_NAME==system_conv_0_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_ooc.xdc

# XDC: bd/system/ip/system_cntr_0_0/system_cntr_0_0_ooc.xdc

# XDC: bd/system/ip/system_fifo_0_0/system_fifo_0_0_ooc.xdc

# XDC: bd/system/ip/system_fifo_0_0/system_fifo_0_0/system_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_fifo_0_0/system_fifo_0_0/system_fifo_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_conv_0_0/system_conv_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
