# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.cache/wt [current_project]
set_property parent.project_path /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/red-pitaya/red-pitaya-notes/tmp/cores [current_project]
set_property verilog_define TOOL_VIVADO [current_fileset]
add_files /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_cntr_0_0/system_cntr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_fifo_0_0/system_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_fifo_0_0/system_fifo_0_0/system_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_fifo_0_0/system_fifo_0_0/system_fifo_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_conv_0_0/system_conv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib /home/red-pitaya/red-pitaya-notes/tmp/adc_recorder.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc /home/red-pitaya/red-pitaya-notes/cfg/ports.xdc
set_property used_in_implementation false [get_files /home/red-pitaya/red-pitaya-notes/cfg/ports.xdc]

read_xdc /home/red-pitaya/red-pitaya-notes/cfg/clocks.xdc
set_property used_in_implementation false [get_files /home/red-pitaya/red-pitaya-notes/cfg/clocks.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_wrapper -part xc7z010clg400-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
